### ISSUE TITLE
Open CSV file in Python3

### ISSUE THREAD

**Issue by aguyoung** [japs/alipy#4]
Hi, 
Thank you for share the code, it has been very helpfull to our astronomy project.
I found a small bugfix on alipy/align.py:208
The parameter 'b' must be removed in order to exec with python3.
Take a look on https://stackoverflow.com/questions/34283178/typeerror-a-bytes-like-object-is-required-not-str-in-python-and-csv
I could make a pull request if you prefer, but you should give me permissions.
Thank you.
PD: This is my fist public contribution :sunglasses:

**Comment by japs** [comment]
Hi Agustín,
thanks a lot for the contribution. Not an expert of github here, but I think the standard procedure is that you clone the project to your account, make the changes and then send me the pull request from there. There is no permission from my side involved.

Thanks again! j
